sudo: required

services:
  - docker

before_install:
  - docker build -t subhashsitian/docker-react -f Dockerfile.dev .

script:
  - docker run subhashsitian/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DoctorReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-792292766624"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECERET_KEY"
