sudo: required

services:
  - docker

before_install:
  - docker build -t subhashsitian/docker-react -f Dockerfile.dev .
  
script:
  - docker run subhashsitian/docker-react npm run test -- --coverage